language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_script:
  - echo $GOPATH
  - echo $PATH
  - go get -d github.com/ipfs/go-ipfs
  - pushd . && cd $GOPATH/src/github.com/ipfs/go-ipfs && make install && popd
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - ipfs init
  - ipfs daemon &
  - tox -e pep8
  - tox
