language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.3"
    env: TOXENV=py33
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
before_script:
  - eval "$(gimme 1.6.2)"
  - mkdir $HOME/go
  - export GOPATH="$HOME/go"
  - export PATH="$PATH:$GOPATH/bin"
  - echo $GOPATH
  - echo $PATH
  - go get -d github.com/ipfs/go-ipfs
  - pushd . && cd $GOPATH/src/github.com/ipfs/go-ipfs && make install && popd
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - ipfs init
  - ipfs daemon &
  - tox -e pep8
  - tox
