language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_script:
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.2/go-ipfs_v0.4.2_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - tar -xzvf /tmp/ipfs.tar.gz
  - mv go-ipfs/ipfs /usr/local/bin/ipfs
  - ipfs daemon &
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - tox -e pep8
  - tox
